env:
  browser: true
  es6: true
extends: airbnb
rules:
  no-use-before-define:
    - 0
  object-curly-spacing:
    - 2
    - "never"
  semi:
    - 2
    - "never"
    - beforeStatementContinuationChars: "always"
